<a href="https://colab.research.google.com/github/Vania12San/analisis-datos-i/blob/main/portafolio_adi_vasc_p01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TEMA ELEGIDO

MERCADOTECNIA ESTRATÉGICA- "QUIEN ES QUIEN EN LOS PRECIOS"

In [ ]:
library(readr)

In [ ]:
datos <- read_csv("11-2025_01.csv")

Rows: 486182 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (12): producto, presentacion, marca, categoria, catalogo, fecha_registro...
dbl  (1): precio

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [ ]:
datos

       producto
1      Aceite
2      Arroz
3      Atún
4      Atún
5      Azúcar
6      Azúcar
7      Carne Cerdo
8      Carne Cerdo
9      Carne Cerdo
10     Carne Pollo
11     Carne Pollo
12     Carne Pollo
13     Carne Pollo
14     Carne Pollo
15     Carne Res
16     Carne Res
17     Carne Res
18     Carne Res
19     Cebolla
20     Cebolla
21     Chile Fresco
22     Frijol
23     Huevo
24     Jabón de Tocador
25     Jabón de Tocador
26     Jitomate
27     Jitomate
28     Leche Ultrapasteurizada
29     Leche Ultrapasteurizada
30     Limón
⋮      ⋮
486153 Electrónicos de Video
486154 Electrónicos de Video
486155 Electrónicos de Video
486156 Electrónicos de Video
486157 Electrónicos de Video
486158 Electrónicos de Video
486159 Extractores de Jugos y Exprimidores
486160 Extractores de Jugos y Exprimidores
486161 Extractores de Jugos y Exprimidores
486162 Freidoras de Aire
486163 Horno de Microondas
486164 Horno Eléctrico
486165 Lavadoras
486166 Lavadoras
486167 Lavadoras
486168 Licuadoras
486169 Licuadoras
486170 Pantallas
486171 Pantallas
486172 Pantallas
486173 Planchas
486174 Refrigeradores
486175 Refrigeradores
486176 Refrigeradores
486177 Refrigeradores
486178 Reproductores Streaming
486179 Secadoras
486180 Tablet
486181 Tablet
486182 Tostadores de Pan
       presentacion
1      Botella 850 Ml. Vegetal
2      Bolsa 900 Gr. Extra. Grano Largo
3      Lata 140 Gr. Desmenuzado en Aceite. Standard, Sin Soya
4      Lata 140 Gr. Desmenuzado en Agua. Standard, Sin Soya
5      Bolsa Plástico 900 Gr. Estándar
6      Bolsa Plástico 900 Gr. Estándar
7      1 Kg. Granel. Chuleta o Chuleta Natural o Fresca/chuleta de Puerco Entrecortada o Lomo Deshuesado de Puerco o Chuleta Natural Lomo de Puerco
8      1 Kg. Granel. Pulpa en Trocitos
9      1 Kg. Granel. Pulpa en Trozo
10     1 Kg. Granel. Entero
11     1 Kg. Granel. Entero
12     1 Kg. Granel. Entero. con Vísceras o Tipo Super o Entero Supermercado o Canal Entera
13     1 Kg. Granel. Pierna con Muslo. Corte Americano
14     1 Kg. Granel. Pierna con Muslo. Pigmentada
15     1 Kg. Granel. Bistec Flecha para Asar
16     1 Kg. Granel. Bistec/chuleta del 0
17     1 Kg. Granel. Carne para Asar
18     1 Kg. Granel. Costilla para Asar. Rdfs
19     1 Kg. Granel. Blanca Sin Rabo
20     1 Kg. Granel. Morada
21     1 Kg. Granel. Jalapeño o Cuaresmeño
22     Bolsa 908 Gr. Negro
23     Paquete C/18 Blanco
24     Barra 135 Gr. Neutro
25     Barra 135 Gr. Neutro
26     1 Kg. Granel. Bola/sinaloa o Tomate Bola
27     1 Kg. Granel. Saladette/huaje o Tomate Saladette/huaje
28     Bolsa 1 Lt. Entera
29     Envase o Caja 1 Lt. Entera
30     1 Kg. Granel. Agrio con Semilla o Colima
⋮      ⋮
486153 X Box. Series S. 1 Tb Ssd. Sin Juego Incluido
486154 Switch 2. Azul con Rojo. 256 Gb. Sin Juego Incluido
486155 Switch 2. Mario Kart World Bundle. 256 Gb. Mario Kart World. Descarga Digital
486156 Switch. Neon. Mario Kart 8. 32 Gb. Mario Kart 8 (descarga)
486157 Ps5. Astro Bot-gran Turismo 7. 1 Tb. Astro Bot-gran Turismo 7. Descarga Digital
486158 Ps5. Returnal-ratchet & Clank. Digital. Cfi-2015. 1 Tb. Returnal- Ratchet & Clank (descarga).
486159 Fpstju407b o Fpstju407b-013. Exprimidor
486160 Ze420dmx. Extractor
486161 Zp520dmx. Exprimidor
486162 Ey505850. Capacidad 4.2 L. y Parilla
486163 Ms3032jas. 1.05 Pies Cúbicos. Color Negro/espejo
486164 Tssttv7030-1mx
486165 Wdqy 1514. 15/10 Kg. Tambor. Centrifugado y Secado. Color Gris
486166 Lma 70214 Vbab0 o Vbab01 o Vbab02 o Vbab03. 21 Kg. Agitador. Centrifugado. Color Blanca
486167 Lma 77113 Cbab0 o Cbab04. 17 Kg. Agitador. Centrifugado. Color Blanco
486168 Pb2004g. Velocidades 2+1 Pulso. Base Acero. Vaso Plástico. Color Plata
486169 Blstkap-wpb o Blstkap-wpb-013. Velocidades 2 + 1 Pulso. Base Plástico. Vaso Vidrio. Color Blanca
486170 58a6nv. 58 Plgs. Uled. Puerto Usb. Smart Tv.
486171 75a65nv. 75 Plgs. Led. Puerto Usb. Smart Tv.
486172 65 Ur 7800 Psb. 65 Plgs. Led. Puerto Usb. Smart Tv.
486173 Fv6811 o Fv6811xo. Vapor. Suela Durilium Airglide
486174 Rr 63d6 Wgx (silver). 173 Dm3. 1 Puertavertical. Deshielo Semiautomático
486175 Rmb 400 Ia (mrm0) (silver). 400 L. 2 Puertas, Horizontal y Vertical. Deshielo Automático Ajustable
486176 Rf 22 A4010 S9. 628 Dm3. 3 Puertas, 2 Verticales y 1 Horizontal. Deshielo Automático de Duración Larga
486177 Rs 28 T5 B00b1 (negro). 798 Dm3. 2 Puertas, Verticales. Deshielo Automático de Duración Larga
486178 Streaming Stick 4k o 3820mx
486179 Smg26n5mn Bab0 o Bab00 o Bab01. 20 Kgs. Gas. Color Blanca
486180 Tab M11. Tb330fu. 11 Plgs. Memoria Interna 128 Gb. Memoria Ram 8 Gb.
486181 Tab One. Tb305fu. 8.7 Plgs. Memoria Interna 128 Gb. Memoria Ram 4 Gb.
486182 Tssttr500 o Tssttr500-013
       marca                  categoria
1      Precíssimo             Aceites y Grasas Veg. Comestibles
2      Precíssimo             Arroz y Cereales Preparados
3      Fresh Label            Pescados y Mariscos en Conserva
4      Fresh Label            Pescados y Mariscos en Conserva
5      Precíssimo             Azucar
6      Zulka                  Azucar
7      S/m                    Carne y Visceras de Cerdo
8      S/m                    Carne y Visceras de Cerdo
9      S/m                    Carne y Visceras de Cerdo
10     Bachoco                Carne de Ave
11     Pilgrim`s              Carne de Ave
12     S/m                    Carne de Ave
13     S/m                    Carne de Ave
14     S/m                    Carne de Ave
15     S/m                    Carne y Visceras de Res
16     S/m                    Carne y Visceras de Res
17     S/m                    Carne y Visceras de Res
18     S/m                    Carne y Visceras de Res
19     S/m                    Hortalizas Frescas
20     S/m                    Hortalizas Frescas
21     S/m                    Hortalizas Frescas
22     Precíssimo             Legumbres Secas
23     Precíssimo             Huevo
24     Caricia                Arts. para el Cuidado Personal
25     Precíssimo             Arts. para el Cuidado Personal
26     S/m                    Hortalizas Frescas
27     S/m                    Hortalizas Frescas
28     Valley Foods           Leche Procesada
29     Valley Foods           Leche Procesada
30     S/m                    Frutas Frescas
⋮      ⋮                      ⋮
486153 Microsoft              Arts. de Esparcimiento (juguetes)
486154 Nintendo               Arts. de Esparcimiento (juguetes)
486155 Nintendo               Arts. de Esparcimiento (juguetes)
486156 Nintendo               Arts. de Esparcimiento (juguetes)
486157 Sony                   Arts. de Esparcimiento (juguetes)
486158 Sony                   Arts. de Esparcimiento (juguetes)
486159 Oster                  Aparatos Electricos
486160 T-fal. Frutelia Plus   Aparatos Electricos
486161 T-fal. Turbo Press     Aparatos Electricos
486162 T-fal. Easy Fry&grill  Aparatos Electricos
486163 Lg. Smart Diagnosis    Aparatos Electricos
486164 Oster                  Aparatos Electricos
486165 Hisense                Aparatos Electricos
486166 Mabe                   Aparatos Electricos
486167 Mabe                   Aparatos Electricos
486168 Black+decker           Aparatos Electricos
486169 Oster                  Aparatos Electricos
486170 Hisense                Aparatos Electronicos
486171 Hisense                Aparatos Electronicos
486172 Lg                     Aparatos Electronicos
486173 T-fal. Ultragliss Plus Aparatos Electricos
486174 Hisense                Aparatos Electricos
486175 Mabe                   Aparatos Electricos
486176 Samsung                Aparatos Electricos
486177 Samsung                Aparatos Electricos
486178 Roku                   Aparatos Electronicos
486179 Mabe                   Aparatos Electricos
486180 Lenovo                 Aparatos Electronicos
486181 Lenovo                 Aparatos Electronicos
486182 Oster                  Aparatos Electricos
       catalogo          precio fecha_registro cadena_comercial
1      Pacic              26.50 03/11/2025     Mega Soriana
2      Pacic              16.90 03/11/2025     Mega Soriana
3      Pacic              17.90 03/11/2025     Mega Soriana
4      Pacic              17.90 03/11/2025     Mega Soriana
5      Pacic              25.90 03/11/2025     Mega Soriana
6      Pacic              24.90 03/11/2025     Mega Soriana
7      Pacic             128.00 03/11/2025     Mega Soriana
8      Pacic              88.00 03/11/2025     Mega Soriana
9      Pacic              88.00 03/11/2025     Mega Soriana
10     Pacic              44.00 03/11/2025     Mega Soriana
11     Pacic              44.00 03/11/2025     Mega Soriana
12     Pacic              44.00 03/11/2025     Mega Soriana
13     Pacic              38.90 03/11/2025     Mega Soriana
14     Pacic              38.90 03/11/2025     Mega Soriana
15     Pacic             125.60 03/11/2025     Mega Soriana
16     Pacic             204.00 03/11/2025     Mega Soriana
17     Pacic             199.00 03/11/2025     Mega Soriana
18     Pacic             159.00 03/11/2025     Mega Soriana
19     Pacic              36.90 03/11/2025     Mega Soriana
20     Pacic              34.80 03/11/2025     Mega Soriana
21     Pacic              25.90 03/11/2025     Mega Soriana
22     Pacic              29.58 03/11/2025     Mega Soriana
23     Pacic              57.90 03/11/2025     Mega Soriana
24     Pacic              11.50 03/11/2025     Mega Soriana
25     Pacic               3.90 03/11/2025     Mega Soriana
26     Pacic              27.90 03/11/2025     Mega Soriana
27     Pacic              21.80 03/11/2025     Mega Soriana
28     Pacic              14.90 03/11/2025     Mega Soriana
29     Pacic              23.50 03/11/2025     Mega Soriana
30     Pacic              28.80 03/11/2025     Mega Soriana
⋮      ⋮                 ⋮      ⋮              ⋮
486153 Electrodomesticos  8999  15/11/2025     Wal-mart
486154 Electrodomesticos 10990  15/11/2025     Wal-mart
486155 Electrodomesticos 10990  15/11/2025     Wal-mart
486156 Electrodomesticos  5290  15/11/2025     Wal-mart
486157 Electrodomesticos  7149  15/11/2025     Wal-mart
486158 Electrodomesticos  7149  15/11/2025     Wal-mart
486159 Electrodomesticos   379  15/11/2025     Wal-mart
486160 Electrodomesticos   999  15/11/2025     Wal-mart
486161 Electrodomesticos   799  15/11/2025     Wal-mart
486162 Electrodomesticos  2199  15/11/2025     Wal-mart
486163 Electrodomesticos  2490  15/11/2025     Wal-mart
486164 Electrodomesticos  2380  15/11/2025     Wal-mart
486165 Electrodomesticos  9990  15/11/2025     Wal-mart
486166 Electrodomesticos  8990  15/11/2025     Wal-mart
486167 Electrodomesticos  7990  15/11/2025     Wal-mart
486168 Electrodomesticos  1199  15/11/2025     Wal-mart
486169 Electrodomesticos   599  15/11/2025     Wal-mart
486170 Electrodomesticos  6490  15/11/2025     Wal-mart
486171 Electrodomesticos 10990  15/11/2025     Wal-mart
486172 Electrodomesticos  8990  15/11/2025     Wal-mart
486173 Electrodomesticos   999  15/11/2025     Wal-mart
486174 Electrodomesticos  4890  15/11/2025     Wal-mart
486175 Electrodomesticos  9990  15/11/2025     Wal-mart
486176 Electrodomesticos 16990  15/11/2025     Wal-mart
486177 Electrodomesticos 18990  15/11/2025     Wal-mart
486178 Electrodomesticos  1190  15/11/2025     Wal-mart
486179 Electrodomesticos  8690  15/11/2025     Wal-mart
486180 Electrodomesticos  2890  15/11/2025     Wal-mart
486181 Electrodomesticos  1990  15/11/2025     Wal-mart
486182 Electrodomesticos   689  15/11/2025     Wal-mart
       giro
1      Supermercado / Tienda de Autoservicio
2      Supermercado / Tienda de Autoservicio
3      Supermercado / Tienda de Autoservicio
4      Supermercado / Tienda de Autoservicio
5      Supermercado / Tienda de Autoservicio
6      Supermercado / Tienda de Autoservicio
7      Supermercado / Tienda de Autoservicio
8      Supermercado / Tienda de Autoservicio
9      Supermercado / Tienda de Autoservicio
10     Supermercado / Tienda de Autoservicio
11     Supermercado / Tienda de Autoservicio
12     Supermercado / Tienda de Autoservicio
13     Supermercado / Tienda de Autoservicio
14     Supermercado / Tienda de Autoservicio
15     Supermercado / Tienda de Autoservicio
16     Supermercado / Tienda de Autoservicio
17     Supermercado / Tienda de Autoservicio
18     Supermercado / Tienda de Autoservicio
19     Supermercado / Tienda de Autoservicio
20     Supermercado / Tienda de Autoservicio
21     Supermercado / Tienda de Autoservicio
22     Supermercado / Tienda de Autoservicio
23     Supermercado / Tienda de Autoservicio
24     Supermercado / Tienda de Autoservicio
25     Supermercado / Tienda de Autoservicio
26     Supermercado / Tienda de Autoservicio
27     Supermercado / Tienda de Autoservicio
28     Supermercado / Tienda de Autoservicio
29     Supermercado / Tienda de Autoservicio
30     Supermercado / Tienda de Autoservicio
⋮      ⋮
486153 Supermercado / Tienda de Autoservicio
486154 Supermercado / Tienda de Autoservicio
486155 Supermercado / Tienda de Autoservicio
486156 Supermercado / Tienda de Autoservicio
486157 Supermercado / Tienda de Autoservicio
486158 Supermercado / Tienda de Autoservicio
486159 Supermercado / Tienda de Autoservicio
486160 Supermercado / Tienda de Autoservicio
486161 Supermercado / Tienda de Autoservicio
486162 Supermercado / Tienda de Autoservicio
486163 Supermercado / Tienda de Autoservicio
486164 Supermercado / Tienda de Autoservicio
486165 Supermercado / Tienda de Autoservicio
486166 Supermercado / Tienda de Autoservicio
486167 Supermercado / Tienda de Autoservicio
486168 Supermercado / Tienda de Autoservicio
486169 Supermercado / Tienda de Autoservicio
486170 Supermercado / Tienda de Autoservicio
486171 Supermercado / Tienda de Autoservicio
486172 Supermercado / Tienda de Autoservicio
486173 Supermercado / Tienda de Autoservicio
486174 Supermercado / Tienda de Autoservicio
486175 Supermercado / Tienda de Autoservicio
486176 Supermercado / Tienda de Autoservicio
486177 Supermercado / Tienda de Autoservicio
486178 Supermercado / Tienda de Autoservicio
486179 Supermercado / Tienda de Autoservicio
486180 Supermercado / Tienda de Autoservicio
486181 Supermercado / Tienda de Autoservicio
486182 Supermercado / Tienda de Autoservicio
       nombre_comercial
1      Mega Soriana Sucursal Aguascalientes
2      Mega Soriana Sucursal Aguascalientes
3      Mega Soriana Sucursal Aguascalientes
4      Mega Soriana Sucursal Aguascalientes
5      Mega Soriana Sucursal Aguascalientes
6      Mega Soriana Sucursal Aguascalientes
7      Mega Soriana Sucursal Aguascalientes
8      Mega Soriana Sucursal Aguascalientes
9      Mega Soriana Sucursal Aguascalientes
10     Mega Soriana Sucursal Aguascalientes
11     Mega Soriana Sucursal Aguascalientes
12     Mega Soriana Sucursal Aguascalientes
13     Mega Soriana Sucursal Aguascalientes
14     Mega Soriana Sucursal Aguascalientes
15     Mega Soriana Sucursal Aguascalientes
16     Mega Soriana Sucursal Aguascalientes
17     Mega Soriana Sucursal Aguascalientes
18     Mega Soriana Sucursal Aguascalientes
19     Mega Soriana Sucursal Aguascalientes
20     Mega Soriana Sucursal Aguascalientes
21     Mega Soriana Sucursal Aguascalientes
22     Mega Soriana Sucursal Aguascalientes
23     Mega Soriana Sucursal Aguascalientes
24     Mega Soriana Sucursal Aguascalientes
25     Mega Soriana Sucursal Aguascalientes
26     Mega Soriana Sucursal Aguascalientes
27     Mega Soriana Sucursal Aguascalientes
28     Mega Soriana Sucursal Aguascalientes
29     Mega Soriana Sucursal Aguascalientes
30     Mega Soriana Sucursal Aguascalientes
⋮      ⋮
486153 Walmart Sucursal Colinas del Padre
486154 Walmart Sucursal Colinas del Padre
486155 Walmart Sucursal Colinas del Padre
486156 Walmart Sucursal Colinas del Padre
486157 Walmart Sucursal Colinas del Padre
486158 Walmart Sucursal Colinas del Padre
486159 Walmart Sucursal Colinas del Padre
486160 Walmart Sucursal Colinas del Padre
486161 Walmart Sucursal Colinas del Padre
486162 Walmart Sucursal Colinas del Padre
486163 Walmart Sucursal Colinas del Padre
486164 Walmart Sucursal Colinas del Padre
486165 Walmart Sucursal Colinas del Padre
486166 Walmart Sucursal Colinas del Padre
486167 Walmart Sucursal Colinas del Padre
486168 Walmart Sucursal Colinas del Padre
486169 Walmart Sucursal Colinas del Padre
486170 Walmart Sucursal Colinas del Padre
486171 Walmart Sucursal Colinas del Padre
486172 Walmart Sucursal Colinas del Padre
486173 Walmart Sucursal Colinas del Padre
486174 Walmart Sucursal Colinas del Padre
486175 Walmart Sucursal Colinas del Padre
486176 Walmart Sucursal Colinas del Padre
486177 Walmart Sucursal Colinas del Padre
486178 Walmart Sucursal Colinas del Padre
486179 Walmart Sucursal Colinas del Padre
486180 Walmart Sucursal Colinas del Padre
486181 Walmart Sucursal Colinas del Padre
486182 Walmart Sucursal Colinas del Padre
       direccion
1      Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
2      Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
3      Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
4      Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
5      Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
6      Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
7      Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
8      Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
9      Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
10     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
11     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
12     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
13     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
14     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
15     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
16     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
17     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
18     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
19     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
20     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
21     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
22     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
23     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
24     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
25     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
26     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
27     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
28     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
29     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
30     Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
⋮      ⋮
486153 Sierra Mapimi 101. Esq. Cerro Ameca. Col. Colinas del Padre. Cp. 98085
486154 Sierra Mapimi 101. Esq. Cerro Ameca. Col. Colinas del Padre. Cp. 98085
486155 Sierra Mapimi 101. Esq. Cerro Ameca. Col. Colinas del Padre. Cp. 98085
486156 Sierra Mapimi 101. Esq. Cerro Ameca. Col. Colinas del Padre. Cp. 98085
486157 Sierra Mapimi 101. Esq. Cerro Ameca. Col. Colinas del Padre. Cp. 98085
486158 Sierra Mapimi 101. Esq. Cerro Ameca. Col. Colinas del Padre. Cp. 98085

In [ ]:
head(datos)

  producto presentacion                                           marca
1 Aceite   Botella 850 Ml. Vegetal                                Precíssimo
2 Arroz    Bolsa 900 Gr. Extra. Grano Largo                       Precíssimo
3 Atún     Lata 140 Gr. Desmenuzado en Aceite. Standard, Sin Soya Fresh Label
4 Atún     Lata 140 Gr. Desmenuzado en Agua. Standard, Sin Soya   Fresh Label
5 Azúcar   Bolsa Plástico 900 Gr. Estándar                        Precíssimo
6 Azúcar   Bolsa Plástico 900 Gr. Estándar                        Zulka
  categoria                         catalogo precio fecha_registro
1 Aceites y Grasas Veg. Comestibles Pacic    26.5   03/11/2025
2 Arroz y Cereales Preparados       Pacic    16.9   03/11/2025
3 Pescados y Mariscos en Conserva   Pacic    17.9   03/11/2025
4 Pescados y Mariscos en Conserva   Pacic    17.9   03/11/2025
5 Azucar                            Pacic    25.9   03/11/2025
6 Azucar                            Pacic    24.9   03/11/2025
  cadena_comercial giro
1 Mega Soriana     Supermercado / Tienda de Autoservicio
2 Mega Soriana     Supermercado / Tienda de Autoservicio
3 Mega Soriana     Supermercado / Tienda de Autoservicio
4 Mega Soriana     Supermercado / Tienda de Autoservicio
5 Mega Soriana     Supermercado / Tienda de Autoservicio
6 Mega Soriana     Supermercado / Tienda de Autoservicio
  nombre_comercial
1 Mega Soriana Sucursal Aguascalientes
2 Mega Soriana Sucursal Aguascalientes
3 Mega Soriana Sucursal Aguascalientes
4 Mega Soriana Sucursal Aguascalientes
5 Mega Soriana Sucursal Aguascalientes
6 Mega Soriana Sucursal Aguascalientes
  direccion
1 Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
2 Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
3 Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
4 Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
5 Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
6 Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col. Trojes de Alonso. Cp. 20116
  estado         municipio
1 Aguascalientes Aguascalientes
2 Aguascalientes Aguascalientes
3 Aguascalientes Aguascalientes
4 Aguascalientes Aguascalientes
5 Aguascalientes Aguascalientes
6 Aguascalientes Aguascalientes

In [ ]:
glimpse(datos)

Rows: 486,182
Columns: 13
$ producto         <chr> "Aceite", "Arroz", "Atún", "Atún", "Azúcar", "Azúcar"…
$ presentacion     <chr> "Botella 850 Ml. Vegetal", "Bolsa 900 Gr. Extra. Gran…
$ marca            <chr> "Precíssimo", "Precíssimo", "Fresh Label", "Fresh Lab…
$ categoria        <chr> "Aceites y Grasas Veg. Comestibles", "Arroz y Cereale…
$ catalogo         <chr> "Pacic", "Pacic", "Pacic", "Pacic", "Pacic", "Pacic",…
$ precio           <dbl> 26.50, 16.90, 17.90, 17.90, 25.90, 24.90, 128.00, 88.…
$ fecha_registro   <chr> "03/11/2025", "03/11/2025", "03/11/2025", "03/11/2025…
$ cadena_comercial <chr> "Mega Soriana", "Mega Soriana", "Mega Soriana", "Mega…
$ giro             <chr> "Supermercado / Tienda de Autoservicio", "Supermercad…
$ nombre_comercial <chr> "Mega Soriana Sucursal Aguascalientes", "Mega Soriana…
$ direccion        <chr> "Aguascalientes Nte. 802. Esq. Blvd. a Zacatecas. Col…
$ estado           <chr> "Aguascalientes", "Aguascalientes", "Aguascalientes",…
$ municipio        <chr> "Aguascalientes", "Aguascalientes", "Aguascalientes",…

## RAZÓN DE ELECCIÓN

Para mi proyecto de Mercadotecnia Estratégica en Google Colab, voy a analizar la base de datos de Profeco para entender cómo interactúan el pricing, la competencia y la segmentación geográfica en el mercado real. Trabajar con estos 486182 registros me permitirá evaluar la enorme dispersión de precios —como la brecha del 212% en el arroz— entre 63 cadenas comerciales y 30 estados, identificando las estrategias de fijación de precios de cada retail (desde Everyday Low Price hasta High-Low Pricing) y determinando cómo varía la sensibilidad al precio según el giro comercial y la ubicación regional.